import blankList from '@/data/blank-covers.json'

/**
 * Event covers that are blank placeholders rather than pictures.
 *
 * ClubTickets serves a solid-black image for some events — the Swedish House
 * Mafia cover is a 1200x806 all-black JPEG, and several events share
 * byte-identical placeholder files. The card then renders a black box, which
 * looks like a broken image but is not: the source simply has no picture in it.
 *
 * The list is generated by `scripts/find-blank-covers.mjs`, which matches on
 * content hash rather than filename or size — the same placeholder is reused
 * across events, and size alone would also catch legitimately small logos.
 * Re-run it after each `sync-clubtickets`.
 */
const BLANK = new Set(blankList as string[])

/** True when this URL is a known blank placeholder. */
export function isBlankCover(url: string | undefined | null): boolean {
  return !!url && BLANK.has(url)
}

/** First usable image from the candidates, skipping known placeholders. */
export function pickCover(...candidates: (string | undefined | null)[]): string {
  for (const c of candidates) {
    if (c && !isBlankCover(c)) return c
  }
  return ''
}

/**
 * Herstelt beeld-URL's die op een hoofdletterextensie eindigen.
 *
 * ClubTickets levert een handvol URL's als `.JPG`; hun opslag is
 * hoofdlettergevoelig en geeft daarop een 403 terwijl exact dezelfde URL met
 * `.jpg` een 200 geeft. Gemeten op de Formentera Cruise:
 *   media.clubtickets.com/event/6a60da41d12e9.JPG  → 403
 *   media.clubtickets.com/event/6a60da41d12e9.jpg  → 200
 *
 * Het zijn er maar twee in de hele feed, maar het gevolg is een pagina zonder
 * enig beeld — precies wat op de Formentera Cruise te zien was. Dit draait bij
 * het inlezen, zodat geen enkele consument er nog last van heeft.
 */
export function fixImageCase(url?: string | null): string {
  if (!url) return ''
  return url.replace(/\.(JPG|JPEG|PNG|WEBP|GIF)(\?|$)/, (_m, ext: string, staart: string) => `.${ext.toLowerCase()}${staart}`)
}
