import type { FeaturedEvent } from '@/types/featured-event'

/**
 * Static fallback events shown when the featured_events table is empty
 * or Supabase is not yet connected. Replace with real DB data by running
 * supabase/migrations/002_featured_events.sql.
 */
export const FALLBACK_FEATURED_EVENTS: FeaturedEvent[] = [
  {
    id: 'fallback-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'Cocoon with Sven Väth',
    subtitle: 'The legendary minimal techno night returns',
    description: null,
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=85',
    category: 'club-ticket',
    venue_name: 'Amnesia',
    event_date: '2026-07-15',
    price_from: 45,
    currency: 'EUR',
    badge_text: 'Iconic Night',
    cta_label: 'Get Tickets',
    cta_href: '/club-tickets/amnesia',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 1,
    active: true,
  },
  {
    id: 'fallback-2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'Flower Power',
    subtitle: "Ibiza's longest-running themed party",
    description: null,
    image_url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=85',
    category: 'club-ticket',
    venue_name: 'Pacha Ibiza',
    event_date: '2026-07-18',
    price_from: 35,
    currency: 'EUR',
    badge_text: 'Every Friday',
    cta_label: 'Get Tickets',
    cta_href: '/club-tickets/pacha',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 2,
    active: true,
  },
  {
    id: 'fallback-3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'Afterlife — Tale of Us',
    subtitle: 'Melodic techno under the stars',
    description: null,
    image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=85',
    category: 'club-ticket',
    venue_name: 'Hi Ibiza',
    event_date: '2026-07-22',
    price_from: 60,
    currency: 'EUR',
    badge_text: 'Selling Fast',
    cta_label: 'Get Tickets',
    cta_href: '/club-tickets/hi-ibiza',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 3,
    active: true,
  },
  {
    id: 'fallback-4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: "David Guetta — F*** Me I'm Famous",
    subtitle: "The world's biggest open-air pool party",
    description: null,
    image_url: 'https://images.unsplash.com/photo-1468359601543-843bfaef291a?w=800&q=85',
    category: 'club-ticket',
    venue_name: 'Ushaia Ibiza',
    event_date: '2026-07-25',
    price_from: 55,
    currency: 'EUR',
    badge_text: 'This Weekend',
    cta_label: 'Get Tickets',
    cta_href: '/club-tickets/ushaia',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 4,
    active: true,
  },
  {
    id: 'fallback-5',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'Exclusive Sunset Charter',
    subtitle: 'Private yacht · Custom route · Es Vedrà to Formentera',
    description: null,
    image_url: 'https://images.unsplash.com/photo-1504735689966-4f12eb87a84e?w=800&q=85',
    category: 'boat-charter',
    venue_name: null,
    event_date: null,
    price_from: 500,
    currency: 'EUR',
    badge_text: 'Most Popular',
    cta_label: 'Enquire Now',
    cta_href: '/private-boat-charters',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 5,
    active: true,
  },
  {
    id: 'fallback-6',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'Ocean Festival Boat Party',
    subtitle: 'Sunset cruise · Live DJs · Open bar included',
    description: null,
    image_url: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=85',
    category: 'boat-party',
    venue_name: null,
    event_date: '2026-07-20',
    price_from: 85,
    currency: 'EUR',
    badge_text: 'Selling Fast',
    cta_label: 'Book Now',
    cta_href: '/boat-parties',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 6,
    active: true,
  },
  {
    id: 'fallback-7',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'VIP Sunset Catamaran',
    subtitle: 'Luxury sailing · Open bar · Catering · Swimming stops',
    description: null,
    image_url: 'https://images.unsplash.com/photo-1527004611998-0c6fde22b1ca?w=800&q=85',
    category: 'catamaran',
    venue_name: null,
    event_date: null,
    price_from: 120,
    currency: 'EUR',
    badge_text: null,
    cta_label: 'Book Now',
    cta_href: '/vip-catamaran',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 7,
    active: true,
  },
  {
    id: 'fallback-8',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    title: 'Formentera Full Day Trip',
    subtitle: "Crystal water · White sand · The world's most beautiful island",
    description: null,
    image_url: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=85',
    category: 'formentera',
    venue_name: null,
    event_date: null,
    price_from: 80,
    currency: 'EUR',
    badge_text: 'Day Trip',
    cta_label: 'Book Now',
    cta_href: '/formentera-boat-trips',
    booking_type: 'internal_link',
    external_url: null,
    sort_order: 8,
    active: true,
  },
]
