import type { ClubEvent } from '@/types/club'

/**
 * Static fallback events shown per club when the events table is empty
 * or Supabase is not yet connected. Keyed by club slug.
 */
export const FALLBACK_CLUB_EVENTS: Record<string, ClubEvent[]> = {
  amnesia: [
    {
      id: 'fb-amnesia-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Cocoon with Sven Väth',
      slug: 'cocoon-sven-vath-july',
      description: 'The legendary minimal techno night returns. Sven Väth leads an all-night journey through the most hypnotic corners of electronic music.',
      image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=85',
      event_date: '2026-07-15',
      doors_open: '00:00',
      price_from: 45,
      currency: 'EUR',
      lineup: ['Sven Väth', 'Stephan Bodzin', 'Dixon'],
      genre_tags: ['Minimal Techno', 'Deep Techno'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
    {
      id: 'fb-amnesia-2',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Cocoon with Sven Väth',
      slug: 'cocoon-sven-vath-august',
      description: 'Round two of the iconic Cocoon residency. Expect an intimate, hypnotic night in the Terrace.',
      image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=85',
      event_date: '2026-08-12',
      doors_open: '00:00',
      price_from: 45,
      currency: 'EUR',
      lineup: ['Sven Väth', 'Loco Dice', 'Rebekah'],
      genre_tags: ['Techno', 'Industrial'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: false,
      published: true,
    },
    {
      id: 'fb-amnesia-3',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Amnesia Opening Party 2026',
      slug: 'amnesia-opening-2026',
      description: 'The most anticipated night of the season. Amnesia opens its doors for another legendary summer.',
      image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=85',
      event_date: '2026-06-10',
      doors_open: '23:00',
      price_from: 50,
      currency: 'EUR',
      lineup: ['Tale of Us', 'Maceo Plex', 'Nina Kraviz'],
      genre_tags: ['Melodic Techno', 'Electronic'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
  ],

  pacha: [
    {
      id: 'fb-pacha-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Flower Power',
      slug: 'flower-power-pacha-july',
      description: "Ibiza's longest-running themed party. Dress up in 60s/70s style and dance to the best flower power anthems all night long.",
      image_url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=85',
      event_date: '2026-07-18',
      doors_open: '23:00',
      price_from: 35,
      currency: 'EUR',
      lineup: ['Various Artists'],
      genre_tags: ['Disco', '70s', 'Funk'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
    {
      id: 'fb-pacha-2',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Flower Power',
      slug: 'flower-power-pacha-august',
      description: "Don't miss the August edition of the world-famous Flower Power at Pacha.",
      image_url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=85',
      event_date: '2026-08-08',
      doors_open: '23:00',
      price_from: 35,
      currency: 'EUR',
      lineup: ['Various Artists'],
      genre_tags: ['Disco', 'Funk'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: false,
      published: true,
    },
    {
      id: 'fb-pacha-3',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Glitterbox',
      slug: 'glitterbox-pacha-july',
      description: "Simon Dunmore's glorious house music party returns to Pacha. A night of pure joy.",
      image_url: 'https://images.unsplash.com/photo-1468359601543-843bfaef291a?w=800&q=85',
      event_date: '2026-07-25',
      doors_open: '23:30',
      price_from: 40,
      currency: 'EUR',
      lineup: ['Simon Dunmore', 'Melvo Baptiste', 'Sister Sledge'],
      genre_tags: ['Disco House', 'Nu-Disco'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
  ],

  'hi-ibiza': [
    {
      id: 'fb-hi-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Afterlife — Tale of Us',
      slug: 'afterlife-hi-ibiza-july',
      description: 'Melodic techno under the stars. Tale of Us bring their Afterlife label to Hi Ibiza for another unforgettable season.',
      image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=85',
      event_date: '2026-07-22',
      doors_open: '23:00',
      price_from: 60,
      currency: 'EUR',
      lineup: ['Tale of Us', 'Agents of Time', 'WhoMadeWho'],
      genre_tags: ['Melodic Techno', 'Progressive House'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
    {
      id: 'fb-hi-2',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Afterlife — Tale of Us',
      slug: 'afterlife-hi-ibiza-august',
      description: 'The second edition of Afterlife this season — expect an even more emotional journey through sound.',
      image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=85',
      event_date: '2026-08-19',
      doors_open: '23:00',
      price_from: 65,
      currency: 'EUR',
      lineup: ['Tale of Us', 'Recondite', 'Moderat Live'],
      genre_tags: ['Melodic Techno', 'Electronic'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: false,
      published: true,
    },
  ],

  ushaia: [
    {
      id: 'fb-ushaia-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: "David Guetta — F*** Me I'm Famous",
      slug: 'david-guetta-ushaia-july',
      description: "The world's biggest open-air pool party. David Guetta headlines his legendary FMIF at the iconic Ushaia outdoor stage.",
      image_url: 'https://images.unsplash.com/photo-1468359601543-843bfaef291a?w=800&q=85',
      event_date: '2026-07-25',
      doors_open: '16:00',
      price_from: 55,
      currency: 'EUR',
      lineup: ['David Guetta', 'Martin Solveig'],
      genre_tags: ['House', 'EDM'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
    {
      id: 'fb-ushaia-2',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: "David Guetta — F*** Me I'm Famous",
      slug: 'david-guetta-ushaia-august',
      description: "Don't miss the August edition of the world-famous FMIF pool party at Ushaia.",
      image_url: 'https://images.unsplash.com/photo-1468359601543-843bfaef291a?w=800&q=85',
      event_date: '2026-08-22',
      doors_open: '16:00',
      price_from: 55,
      currency: 'EUR',
      lineup: ['David Guetta', 'Akon'],
      genre_tags: ['House', 'EDM'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: false,
      published: true,
    },
  ],

  'es-paradis': [
    {
      id: 'fb-paradis-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Water Party',
      slug: 'water-party-es-paradis-july',
      description: "The most spectacular night in Ibiza. Es Paradis floods its dancefloor as the legendary Water Party transforms the venue into a unique spectacle.",
      image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=85',
      event_date: '2026-07-29',
      doors_open: '23:00',
      price_from: 35,
      currency: 'EUR',
      lineup: ['Various Artists'],
      genre_tags: ['House', 'Electronic'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
  ],

  'ibiza-rocks': [
    {
      id: 'fb-rocks-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Ibiza Rocks Weekend',
      slug: 'ibiza-rocks-weekend-august',
      description: 'Live bands, DJs, and pool sessions. The Ibiza Rocks hotel pool stage is legendary for its live acts and electric atmosphere.',
      image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=85',
      event_date: '2026-08-08',
      doors_open: '14:00',
      price_from: 40,
      currency: 'EUR',
      lineup: ['Various Live Acts', 'Guest DJs'],
      genre_tags: ['Live Music', 'Rock', 'Indie'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: true,
      published: true,
    },
  ],

  'o-beach': [
    {
      id: 'fb-obeach-1',
      created_at: new Date().toISOString(),
      club_id: 'fallback',
      title: 'Pool Party & Foam Party',
      slug: 'pool-foam-party-obeach',
      description: 'Day-to-night pool madness at O Beach — the family-friendly option that gets wild after dark.',
      image_url: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=85',
      event_date: '2026-08-05',
      doors_open: '11:00',
      price_from: 30,
      currency: 'EUR',
      lineup: ['Resident DJs'],
      genre_tags: ['House', 'Commercial'],
      booking_type: 'whatsapp',
      promoter_url: null,
      sold_out: false,
      featured: false,
      published: true,
    },
  ],
}
