const fs = require('fs');
const path = require('path');

const locales = ['nl', 'en', 'de', 'es', 'fr'];

const translations = {
  nl: {
    cat_deals_title: "Deals of the Day",
    cat_deals_desc: "Ontdek de scherpste aanbiedingen en last-minute kortingen voor de heetste events van vandaag.",
    cat_clubtickets_title: "Club Tickets",
    cat_clubtickets_desc: "Beleef de beste clubavonden op Ibiza. Koop je tickets veilig en snel en sla de wachtrijen over.",
    cat_artists_title: "Artiesten",
    cat_artists_desc: "Ontdek welke wereldberoemde DJ's deze zomer op Ibiza draaien. Bekijk hun line-ups en boek direct je tickets.",
    cat_boatparties_title: "Bootfeesten",
    cat_boatparties_desc: "Dans op de golven met de beste dj's tijdens een onvergetelijke zonsondergang op de Middellandse Zee.",
    cat_privateboat_title: "Private Boat Charters",
    cat_privateboat_desc: "Huur je eigen privéjacht voor een exclusieve ervaring op zee. Perfect voor vriendengroepen en speciale gelegenheden.",
    cat_formentera_title: "Formentera Trips",
    cat_formentera_desc: "Ontdek het adembenemende zustereiland Formentera. Helderblauw water en witte zandstranden wachten op je.",
    cat_vipcatamaran_title: "VIP Catamaran",
    cat_vipcatamaran_desc: "Ervaar ultieme luxe op een spectaculaire catamaran, compleet met VIP-service, drankjes en entertainment.",
    cat_drinks_title: "Drankpakketten",
    cat_drinks_desc: "Maak je clubavond compleet met onze premium drankpakketten en exclusieve flessenservice.",
    cat_carrental_title: "Car & Scooter Rental",
    cat_carrental_desc: "Verken het eiland in je eigen tempo. Huur betrouwbaar en snel een auto of scooter zonder gedoe.",
    cat_guestlist_title: "Gastenlijst",
    cat_guestlist_desc: "Meld je aan voor de exclusieve gastenlijsten van de beste feesten en profiteer van VIP-voordelen.",
    cat_tips_title: "Ibiza Tips",
    cat_tips_desc: "Onze insider tips en hotspots. Ontdek de verborgen parels, beste restaurants en mooiste stranden.",
    cat_blog_title: "Blog",
    cat_blog_desc: "Lees de laatste nieuwtjes, trends en verhalen over het partyleven en de cultuur op Ibiza.",
    cat_free_title: "Free & Discount Ibiza",
    cat_free_desc: "Bespaar op je vakantie met onze gratis toegangen, kortingscodes en speciale aanbiedingen.",
    cat_discover: "Ontdek",
    cat_view_all_info: "Bekijk alle informatie en mogelijkheden voor",
    cat_on_our_special_page: "op onze speciale pagina.",
    cat_view: "Bekijken",
    cat_view_all: "Bekijk alle",
    cat_top_artists: "Top Artiesten",
    cat_featured: "Uitgelicht",
    home_explore_locations: "Ontdek de top locaties in Ibiza"
  },
  en: {
    cat_deals_title: "Deals of the Day",
    cat_deals_desc: "Discover the best offers and last-minute discounts for today's hottest events.",
    cat_clubtickets_title: "Club Tickets",
    cat_clubtickets_desc: "Experience the best club nights in Ibiza. Buy your tickets safely and skip the queues.",
    cat_artists_title: "Artists",
    cat_artists_desc: "Discover which world-famous DJs are playing in Ibiza this summer. View line-ups and book tickets.",
    cat_boatparties_title: "Boat Parties",
    cat_boatparties_desc: "Dance on the waves with the best DJs during an unforgettable Mediterranean sunset.",
    cat_privateboat_title: "Private Boat Charters",
    cat_privateboat_desc: "Rent your own private yacht for an exclusive experience. Perfect for friends and special occasions.",
    cat_formentera_title: "Formentera Trips",
    cat_formentera_desc: "Discover the breathtaking sister island of Formentera. Crystal clear waters and white sandy beaches await.",
    cat_vipcatamaran_title: "VIP Catamaran",
    cat_vipcatamaran_desc: "Experience ultimate luxury on a spectacular catamaran with VIP service, drinks, and entertainment.",
    cat_drinks_title: "Drink Packages",
    cat_drinks_desc: "Complete your club night with our premium drink packages and exclusive bottle service.",
    cat_carrental_title: "Car & Scooter Rental",
    cat_carrental_desc: "Explore the island at your own pace. Rent a car or scooter reliably and quickly without hassle.",
    cat_guestlist_title: "Guestlist",
    cat_guestlist_desc: "Sign up for exclusive guestlists at the best parties and enjoy VIP benefits.",
    cat_tips_title: "Ibiza Tips",
    cat_tips_desc: "Our insider tips and hotspots. Discover hidden gems, best restaurants, and beautiful beaches.",
    cat_blog_title: "Blog",
    cat_blog_desc: "Read the latest news, trends, and stories about party life and culture in Ibiza.",
    cat_free_title: "Free & Discount Ibiza",
    cat_free_desc: "Save on your vacation with our free entries, discount codes, and special offers.",
    cat_discover: "Discover",
    cat_view_all_info: "View all information and options for",
    cat_on_our_special_page: "on our special page.",
    cat_view: "View",
    cat_view_all: "View all",
    cat_top_artists: "Top Artists",
    cat_featured: "Featured",
    home_explore_locations: "Discover the top locations in Ibiza"
  },
  de: {
    cat_deals_title: "Angebote des Tages",
    cat_deals_desc: "Entdecken Sie die besten Angebote und Last-Minute-Rabatte für die heißesten Events von heute.",
    cat_clubtickets_title: "Club-Tickets",
    cat_clubtickets_desc: "Erleben Sie die besten Clubnächte auf Ibiza. Kaufen Sie Ihre Tickets sicher und überspringen Sie die Warteschlangen.",
    cat_artists_title: "Künstler",
    cat_artists_desc: "Finden Sie heraus, welche weltberühmten DJs diesen Sommer auf Ibiza auflegen. Line-ups ansehen und buchen.",
    cat_boatparties_title: "Bootpartys",
    cat_boatparties_desc: "Tanzen Sie auf den Wellen mit den besten DJs bei einem unvergesslichen Sonnenuntergang im Mittelmeer.",
    cat_privateboat_title: "Private Boot-Charter",
    cat_privateboat_desc: "Mieten Sie Ihre eigene private Yacht für ein exklusives Erlebnis. Perfekt für Freunde und Anlässe.",
    cat_formentera_title: "Formentera Ausflüge",
    cat_formentera_desc: "Entdecken Sie die atemberaubende Schwesterinsel Formentera. Kristallklares Wasser und weiße Sandstrände.",
    cat_vipcatamaran_title: "VIP-Katamaran",
    cat_vipcatamaran_desc: "Erleben Sie ultimativen Luxus auf einem spektakulären Katamaran mit VIP-Service und Unterhaltung.",
    cat_drinks_title: "Getränkepakete",
    cat_drinks_desc: "Vervollständigen Sie Ihre Clubnacht mit unseren Premium-Getränkepaketen und exklusivem Flaschenservice.",
    cat_carrental_title: "Auto- & Rollervermietung",
    cat_carrental_desc: "Erkunden Sie die Insel in Ihrem eigenen Tempo. Mieten Sie zuverlässig und schnell ohne Stress.",
    cat_guestlist_title: "Gästeliste",
    cat_guestlist_desc: "Melden Sie sich für exklusive Gästelisten an und genießen Sie VIP-Vorteile.",
    cat_tips_title: "Ibiza Tipps",
    cat_tips_desc: "Unsere Insider-Tipps und Hotspots. Entdecken Sie verborgene Schätze und wunderschöne Strände.",
    cat_blog_title: "Blog",
    cat_blog_desc: "Lesen Sie die neuesten Nachrichten, Trends und Geschichten über das Partyleben und die Kultur.",
    cat_free_title: "Kostenloses & Rabatte Ibiza",
    cat_free_desc: "Sparen Sie in Ihrem Urlaub mit unseren kostenlosen Eintritten, Rabattcodes und Sonderangeboten.",
    cat_discover: "Entdecken Sie",
    cat_view_all_info: "Alle Informationen und Optionen für",
    cat_on_our_special_page: "auf unserer speziellen Seite ansehen.",
    cat_view: "Ansehen",
    cat_view_all: "Alle ansehen",
    cat_top_artists: "Top-Künstler",
    cat_featured: "Hervorgehoben",
    home_explore_locations: "Entdecken Sie die Top-Standorte auf Ibiza"
  },
  es: {
    cat_deals_title: "Ofertas del Día",
    cat_deals_desc: "Descubre las mejores ofertas y descuentos de última hora para los eventos de hoy.",
    cat_clubtickets_title: "Entradas de Club",
    cat_clubtickets_desc: "Vive las mejores noches de club en Ibiza. Compra tus entradas de forma segura y sáltate las colas.",
    cat_artists_title: "Artistas",
    cat_artists_desc: "Descubre qué DJs de fama mundial tocan en Ibiza este verano. Ver carteles y reservar entradas.",
    cat_boatparties_title: "Fiestas en Barco",
    cat_boatparties_desc: "Baila sobre las olas con los mejores DJs durante una inolvidable puesta de sol en el Mediterráneo.",
    cat_privateboat_title: "Alquiler de Barcos Privados",
    cat_privateboat_desc: "Alquila tu propio yate privado para una experiencia exclusiva. Perfecto para amigos y eventos especiales.",
    cat_formentera_title: "Viajes a Formentera",
    cat_formentera_desc: "Descubre la impresionante isla hermana de Formentera. Aguas cristalinas y playas de arena blanca.",
    cat_vipcatamaran_title: "Catamarán VIP",
    cat_vipcatamaran_desc: "Experimenta el máximo lujo en un espectacular catamarán con servicio VIP, bebidas y entretenimiento.",
    cat_drinks_title: "Paquetes de Bebidas",
    cat_drinks_desc: "Completa tu noche de club con nuestros paquetes de bebidas premium y servicio exclusivo de botellas.",
    cat_carrental_title: "Alquiler de Coches y Motos",
    cat_carrental_desc: "Explora la isla a tu propio ritmo. Alquila un coche o scooter de forma fiable y rápida sin complicaciones.",
    cat_guestlist_title: "Lista de Invitados",
    cat_guestlist_desc: "Inscríbete en listas de invitados exclusivas en las mejores fiestas y disfruta de ventajas VIP.",
    cat_tips_title: "Consejos de Ibiza",
    cat_tips_desc: "Nuestros consejos y lugares destacados. Descubre joyas ocultas, los mejores restaurantes y playas.",
    cat_blog_title: "Blog",
    cat_blog_desc: "Lee las últimas noticias, tendencias e historias sobre la vida nocturna y la cultura de Ibiza.",
    cat_free_title: "Ibiza Gratis y con Descuento",
    cat_free_desc: "Ahorra en tus vacaciones con nuestras entradas gratuitas, códigos de descuento y ofertas especiales.",
    cat_discover: "Descubrir",
    cat_view_all_info: "Ver toda la información y opciones de",
    cat_on_our_special_page: "en nuestra página especial.",
    cat_view: "Ver",
    cat_view_all: "Ver todo",
    cat_top_artists: "Mejores Artistas",
    cat_featured: "Destacado",
    home_explore_locations: "Descubre los mejores lugares de Ibiza"
  },
  fr: {
    cat_deals_title: "Offres du Jour",
    cat_deals_desc: "Découvrez les meilleures offres et réductions de dernière minute pour les événements du jour.",
    cat_clubtickets_title: "Billets de Club",
    cat_clubtickets_desc: "Vivez les meilleures soirées d'Ibiza. Achetez vos billets en toute sécurité et évitez les files d'attente.",
    cat_artists_title: "Artistes",
    cat_artists_desc: "Découvrez quels DJs de renommée mondiale mixent à Ibiza cet été. Voir les programmations.",
    cat_boatparties_title: "Fêtes en Bateau",
    cat_boatparties_desc: "Dansez sur les vagues avec les meilleurs DJs lors d'un coucher de soleil méditerranéen inoubliable.",
    cat_privateboat_title: "Location de Bateaux Privés",
    cat_privateboat_desc: "Louez votre propre yacht privé pour une expérience exclusive. Parfait pour les amis et occasions.",
    cat_formentera_title: "Excursions à Formentera",
    cat_formentera_desc: "Découvrez la magnifique île de Formentera. Des eaux cristallines et des plages de sable blanc.",
    cat_vipcatamaran_title: "Catamaran VIP",
    cat_vipcatamaran_desc: "Vivez le luxe ultime sur un catamaran spectaculaire avec service VIP, boissons et divertissements.",
    cat_drinks_title: "Forfaits Boissons",
    cat_drinks_desc: "Complétez votre soirée en club avec nos forfaits boissons premium et service de bouteilles exclusif.",
    cat_carrental_title: "Location de Voitures et Scooters",
    cat_carrental_desc: "Explorez l'île à votre rythme. Louez un véhicule de manière fiable et rapide sans tracas.",
    cat_guestlist_title: "Liste d'Invités",
    cat_guestlist_desc: "Inscrivez-vous sur des listes exclusives et profitez d'avantages VIP lors des meilleures fêtes.",
    cat_tips_title: "Conseils pour Ibiza",
    cat_tips_desc: "Nos astuces et bonnes adresses. Découvrez des joyaux cachés, les meilleurs restaurants et plages.",
    cat_blog_title: "Blog",
    cat_blog_desc: "Lisez les dernières actualités, tendances et histoires sur la vie nocturne et la culture à Ibiza.",
    cat_free_title: "Ibiza Gratuit et Réductions",
    cat_free_desc: "Économisez sur vos vacances avec nos entrées gratuites, codes de réduction et offres spéciales.",
    cat_discover: "Découvrir",
    cat_view_all_info: "Voir toutes les informations et options pour",
    cat_on_our_special_page: "sur notre page spéciale.",
    cat_view: "Voir",
    cat_view_all: "Voir tout",
    cat_top_artists: "Meilleurs Artistes",
    cat_featured: "En vedette",
    home_explore_locations: "Découvrez les meilleurs endroits à Ibiza"
  }
};

const dictsDir = path.join(__dirname, '../src/dictionaries');

locales.forEach(loc => {
  const file = path.join(dictsDir, `${loc}.json`);
  if (fs.existsSync(file)) {
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    const trans = translations[loc];
    for (const key in trans) {
      data[key] = trans[key];
    }
    fs.writeFileSync(file, JSON.stringify(data, null, 2));
    console.log(`Updated ${loc}.json`);
  } else {
    console.warn(`File ${loc}.json not found!`);
  }
});
